//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotServer.DaHuaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.dhsoft.com", ConfigurationName="DaHuaService.MobPhoneService")]
    public interface MobPhoneService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LotServer.DaHuaService.getCardNumberByPhoneResponse getCardNumberByPhone(LotServer.DaHuaService.getCardNumberByPhone request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getCardNumberByPhoneResponse> getCardNumberByPhoneAsync(LotServer.DaHuaService.getCardNumberByPhone request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LotServer.DaHuaService.getCallNumberResponse getCallNumber(LotServer.DaHuaService.getCallNumber request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getCallNumberResponse> getCallNumberAsync(LotServer.DaHuaService.getCallNumber request);
        
        // CODEGEN: 命名空间  的元素名称 getSCService 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LotServer.DaHuaService.getSCServiceResponse getSCService(LotServer.DaHuaService.getSCService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getSCServiceResponse> getSCServiceAsync(LotServer.DaHuaService.getSCService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LotServer.DaHuaService.openDoorResponse openDoor(LotServer.DaHuaService.openDoor request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LotServer.DaHuaService.openDoorResponse> openDoorAsync(LotServer.DaHuaService.openDoor request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LotServer.DaHuaService.getRoomNumByPhoneResponse getRoomNumByPhone(LotServer.DaHuaService.getRoomNumByPhone request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getRoomNumByPhoneResponse> getRoomNumByPhoneAsync(LotServer.DaHuaService.getRoomNumByPhone request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LotServer.DaHuaService.getPublishInfosResponse getPublishInfos(LotServer.DaHuaService.getPublishInfos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getPublishInfosResponse> getPublishInfosAsync(LotServer.DaHuaService.getPublishInfos request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNumberByPhone {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNumberByPhone", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getCardNumberByPhoneBody Body;
        
        public getCardNumberByPhone() {
        }
        
        public getCardNumberByPhone(LotServer.DaHuaService.getCardNumberByPhoneBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCardNumberByPhoneBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getCardNumberByPhoneBody() {
        }
        
        public getCardNumberByPhoneBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNumberByPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNumberByPhoneResponse", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getCardNumberByPhoneResponseBody Body;
        
        public getCardNumberByPhoneResponse() {
        }
        
        public getCardNumberByPhoneResponse(LotServer.DaHuaService.getCardNumberByPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCardNumberByPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCardNumberByPhone;
        
        public getCardNumberByPhoneResponseBody() {
        }
        
        public getCardNumberByPhoneResponseBody(string getCardNumberByPhone) {
            this.getCardNumberByPhone = getCardNumberByPhone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCallNumber {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCallNumber", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getCallNumberBody Body;
        
        public getCallNumber() {
        }
        
        public getCallNumber(LotServer.DaHuaService.getCallNumberBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCallNumberBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getCallNumberBody() {
        }
        
        public getCallNumberBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCallNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCallNumberResponse", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getCallNumberResponseBody Body;
        
        public getCallNumberResponse() {
        }
        
        public getCallNumberResponse(LotServer.DaHuaService.getCallNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCallNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCallNumber;
        
        public getCallNumberResponseBody() {
        }
        
        public getCallNumberResponseBody(string getCallNumber) {
            this.getCallNumber = getCallNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSCService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSCService", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getSCServiceBody Body;
        
        public getSCService() {
        }
        
        public getSCService(LotServer.DaHuaService.getSCServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getSCServiceBody {
        
        public getSCServiceBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSCServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSCServiceResponse", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getSCServiceResponseBody Body;
        
        public getSCServiceResponse() {
        }
        
        public getSCServiceResponse(LotServer.DaHuaService.getSCServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getSCServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getSCService;
        
        public getSCServiceResponseBody() {
        }
        
        public getSCServiceResponseBody(string getSCService) {
            this.getSCService = getSCService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class openDoor {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="openDoor", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.openDoorBody Body;
        
        public openDoor() {
        }
        
        public openDoor(LotServer.DaHuaService.openDoorBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class openDoorBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public openDoorBody() {
        }
        
        public openDoorBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class openDoorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="openDoorResponse", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.openDoorResponseBody Body;
        
        public openDoorResponse() {
        }
        
        public openDoorResponse(LotServer.DaHuaService.openDoorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class openDoorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openDoor;
        
        public openDoorResponseBody() {
        }
        
        public openDoorResponseBody(string openDoor) {
            this.openDoor = openDoor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomNumByPhone {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomNumByPhone", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getRoomNumByPhoneBody Body;
        
        public getRoomNumByPhone() {
        }
        
        public getRoomNumByPhone(LotServer.DaHuaService.getRoomNumByPhoneBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getRoomNumByPhoneBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getRoomNumByPhoneBody() {
        }
        
        public getRoomNumByPhoneBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomNumByPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomNumByPhoneResponse", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getRoomNumByPhoneResponseBody Body;
        
        public getRoomNumByPhoneResponse() {
        }
        
        public getRoomNumByPhoneResponse(LotServer.DaHuaService.getRoomNumByPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getRoomNumByPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRoomNumByPhone;
        
        public getRoomNumByPhoneResponseBody() {
        }
        
        public getRoomNumByPhoneResponseBody(string getRoomNumByPhone) {
            this.getRoomNumByPhone = getRoomNumByPhone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPublishInfos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPublishInfos", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getPublishInfosBody Body;
        
        public getPublishInfos() {
        }
        
        public getPublishInfos(LotServer.DaHuaService.getPublishInfosBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getPublishInfosBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getPublishInfosBody() {
        }
        
        public getPublishInfosBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPublishInfosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPublishInfosResponse", Namespace="http://webservice.dhsoft.com", Order=0)]
        public LotServer.DaHuaService.getPublishInfosResponseBody Body;
        
        public getPublishInfosResponse() {
        }
        
        public getPublishInfosResponse(LotServer.DaHuaService.getPublishInfosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getPublishInfosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPublishInfos;
        
        public getPublishInfosResponseBody() {
        }
        
        public getPublishInfosResponseBody(string getPublishInfos) {
            this.getPublishInfos = getPublishInfos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobPhoneServiceChannel : LotServer.DaHuaService.MobPhoneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobPhoneServiceClient : System.ServiceModel.ClientBase<LotServer.DaHuaService.MobPhoneService>, LotServer.DaHuaService.MobPhoneService {
        
        public MobPhoneServiceClient() {
        }
        
        public MobPhoneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobPhoneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobPhoneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobPhoneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotServer.DaHuaService.getCardNumberByPhoneResponse LotServer.DaHuaService.MobPhoneService.getCardNumberByPhone(LotServer.DaHuaService.getCardNumberByPhone request) {
            return base.Channel.getCardNumberByPhone(request);
        }
        
        public string getCardNumberByPhone(string arg0) {
            LotServer.DaHuaService.getCardNumberByPhone inValue = new LotServer.DaHuaService.getCardNumberByPhone();
            inValue.Body = new LotServer.DaHuaService.getCardNumberByPhoneBody();
            inValue.Body.arg0 = arg0;
            LotServer.DaHuaService.getCardNumberByPhoneResponse retVal = ((LotServer.DaHuaService.MobPhoneService)(this)).getCardNumberByPhone(inValue);
            return retVal.Body.getCardNumberByPhone;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getCardNumberByPhoneResponse> LotServer.DaHuaService.MobPhoneService.getCardNumberByPhoneAsync(LotServer.DaHuaService.getCardNumberByPhone request) {
            return base.Channel.getCardNumberByPhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotServer.DaHuaService.getCardNumberByPhoneResponse> getCardNumberByPhoneAsync(string arg0) {
            LotServer.DaHuaService.getCardNumberByPhone inValue = new LotServer.DaHuaService.getCardNumberByPhone();
            inValue.Body = new LotServer.DaHuaService.getCardNumberByPhoneBody();
            inValue.Body.arg0 = arg0;
            return ((LotServer.DaHuaService.MobPhoneService)(this)).getCardNumberByPhoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotServer.DaHuaService.getCallNumberResponse LotServer.DaHuaService.MobPhoneService.getCallNumber(LotServer.DaHuaService.getCallNumber request) {
            return base.Channel.getCallNumber(request);
        }
        
        public string getCallNumber(string arg0) {
            LotServer.DaHuaService.getCallNumber inValue = new LotServer.DaHuaService.getCallNumber();
            inValue.Body = new LotServer.DaHuaService.getCallNumberBody();
            inValue.Body.arg0 = arg0;
            LotServer.DaHuaService.getCallNumberResponse retVal = ((LotServer.DaHuaService.MobPhoneService)(this)).getCallNumber(inValue);
            return retVal.Body.getCallNumber;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getCallNumberResponse> LotServer.DaHuaService.MobPhoneService.getCallNumberAsync(LotServer.DaHuaService.getCallNumber request) {
            return base.Channel.getCallNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotServer.DaHuaService.getCallNumberResponse> getCallNumberAsync(string arg0) {
            LotServer.DaHuaService.getCallNumber inValue = new LotServer.DaHuaService.getCallNumber();
            inValue.Body = new LotServer.DaHuaService.getCallNumberBody();
            inValue.Body.arg0 = arg0;
            return ((LotServer.DaHuaService.MobPhoneService)(this)).getCallNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotServer.DaHuaService.getSCServiceResponse LotServer.DaHuaService.MobPhoneService.getSCService(LotServer.DaHuaService.getSCService request) {
            return base.Channel.getSCService(request);
        }
        
        public string getSCService() {
            LotServer.DaHuaService.getSCService inValue = new LotServer.DaHuaService.getSCService();
            inValue.Body = new LotServer.DaHuaService.getSCServiceBody();
            LotServer.DaHuaService.getSCServiceResponse retVal = ((LotServer.DaHuaService.MobPhoneService)(this)).getSCService(inValue);
            return retVal.Body.getSCService;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getSCServiceResponse> LotServer.DaHuaService.MobPhoneService.getSCServiceAsync(LotServer.DaHuaService.getSCService request) {
            return base.Channel.getSCServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotServer.DaHuaService.getSCServiceResponse> getSCServiceAsync() {
            LotServer.DaHuaService.getSCService inValue = new LotServer.DaHuaService.getSCService();
            inValue.Body = new LotServer.DaHuaService.getSCServiceBody();
            return ((LotServer.DaHuaService.MobPhoneService)(this)).getSCServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotServer.DaHuaService.openDoorResponse LotServer.DaHuaService.MobPhoneService.openDoor(LotServer.DaHuaService.openDoor request) {
            return base.Channel.openDoor(request);
        }
        
        public string openDoor(string arg0) {
            LotServer.DaHuaService.openDoor inValue = new LotServer.DaHuaService.openDoor();
            inValue.Body = new LotServer.DaHuaService.openDoorBody();
            inValue.Body.arg0 = arg0;
            LotServer.DaHuaService.openDoorResponse retVal = ((LotServer.DaHuaService.MobPhoneService)(this)).openDoor(inValue);
            return retVal.Body.openDoor;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotServer.DaHuaService.openDoorResponse> LotServer.DaHuaService.MobPhoneService.openDoorAsync(LotServer.DaHuaService.openDoor request) {
            return base.Channel.openDoorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotServer.DaHuaService.openDoorResponse> openDoorAsync(string arg0) {
            LotServer.DaHuaService.openDoor inValue = new LotServer.DaHuaService.openDoor();
            inValue.Body = new LotServer.DaHuaService.openDoorBody();
            inValue.Body.arg0 = arg0;
            return ((LotServer.DaHuaService.MobPhoneService)(this)).openDoorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotServer.DaHuaService.getRoomNumByPhoneResponse LotServer.DaHuaService.MobPhoneService.getRoomNumByPhone(LotServer.DaHuaService.getRoomNumByPhone request) {
            return base.Channel.getRoomNumByPhone(request);
        }
        
        public string getRoomNumByPhone(string arg0) {
            LotServer.DaHuaService.getRoomNumByPhone inValue = new LotServer.DaHuaService.getRoomNumByPhone();
            inValue.Body = new LotServer.DaHuaService.getRoomNumByPhoneBody();
            inValue.Body.arg0 = arg0;
            LotServer.DaHuaService.getRoomNumByPhoneResponse retVal = ((LotServer.DaHuaService.MobPhoneService)(this)).getRoomNumByPhone(inValue);
            return retVal.Body.getRoomNumByPhone;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getRoomNumByPhoneResponse> LotServer.DaHuaService.MobPhoneService.getRoomNumByPhoneAsync(LotServer.DaHuaService.getRoomNumByPhone request) {
            return base.Channel.getRoomNumByPhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotServer.DaHuaService.getRoomNumByPhoneResponse> getRoomNumByPhoneAsync(string arg0) {
            LotServer.DaHuaService.getRoomNumByPhone inValue = new LotServer.DaHuaService.getRoomNumByPhone();
            inValue.Body = new LotServer.DaHuaService.getRoomNumByPhoneBody();
            inValue.Body.arg0 = arg0;
            return ((LotServer.DaHuaService.MobPhoneService)(this)).getRoomNumByPhoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LotServer.DaHuaService.getPublishInfosResponse LotServer.DaHuaService.MobPhoneService.getPublishInfos(LotServer.DaHuaService.getPublishInfos request) {
            return base.Channel.getPublishInfos(request);
        }
        
        public string getPublishInfos(string arg0) {
            LotServer.DaHuaService.getPublishInfos inValue = new LotServer.DaHuaService.getPublishInfos();
            inValue.Body = new LotServer.DaHuaService.getPublishInfosBody();
            inValue.Body.arg0 = arg0;
            LotServer.DaHuaService.getPublishInfosResponse retVal = ((LotServer.DaHuaService.MobPhoneService)(this)).getPublishInfos(inValue);
            return retVal.Body.getPublishInfos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LotServer.DaHuaService.getPublishInfosResponse> LotServer.DaHuaService.MobPhoneService.getPublishInfosAsync(LotServer.DaHuaService.getPublishInfos request) {
            return base.Channel.getPublishInfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<LotServer.DaHuaService.getPublishInfosResponse> getPublishInfosAsync(string arg0) {
            LotServer.DaHuaService.getPublishInfos inValue = new LotServer.DaHuaService.getPublishInfos();
            inValue.Body = new LotServer.DaHuaService.getPublishInfosBody();
            inValue.Body.arg0 = arg0;
            return ((LotServer.DaHuaService.MobPhoneService)(this)).getPublishInfosAsync(inValue);
        }
    }
}
